// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Mira struct {
	Idp      int32  `json:"idp"`
	Idu      int32  `json:"idu"`
	Gustoono string `json:"gustoono"`
	Calif    int32  `json:"calif"`
}

type Pelicula struct {
	Idp      int32  `json:"idp"`
	Titulo   string `json:"titulo"`
	Duracion int32  `json:"duracion"`
	Director string `json:"director"`
	Actores  string `json:"actores"`
	Edadmin  int32  `json:"edadmin"`
	Sinopsis string `json:"sinopsis"`
	Anioestr int32  `json:"anioestr"`
}

type Usuario struct {
	Idu         int32     `json:"idu"`
	Nomusu      string    `json:"nomusu"`
	Contrasenia string    `json:"contrasenia"`
	Email       string    `json:"email"`
	Fechanac    time.Time `json:"fechanac"`
}
