// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queriesUsuario.sql

package db

import (
	"context"
	"time"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuario (nomUsu, contrasenia, email, fechaNac) VALUES ($1, $2, $3, $4) RETURNING idu, nomusu, contrasenia, email, fechanac
`

type CreateUsuarioParams struct {
	Nomusu      string    `json:"nomusu"`
	Contrasenia string    `json:"contrasenia"`
	Email       string    `json:"email"`
	Fechanac    time.Time `json:"fechanac"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.Nomusu,
		arg.Contrasenia,
		arg.Email,
		arg.Fechanac,
	)
	var i Usuario
	err := row.Scan(
		&i.Idu,
		&i.Nomusu,
		&i.Contrasenia,
		&i.Email,
		&i.Fechanac,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuario WHERE IDU = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idu int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idu)
	return err
}

const getUsuario = `-- name: GetUsuario :one
SELECT idu, nomusu, contrasenia, email, fechanac FROM usuario WHERE IDU = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idu int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idu)
	var i Usuario
	err := row.Scan(
		&i.Idu,
		&i.Nomusu,
		&i.Contrasenia,
		&i.Email,
		&i.Fechanac,
	)
	return i, err
}

const listUsuario = `-- name: ListUsuario :many
SELECT idu, nomusu, contrasenia, email, fechanac FROM usuario ORDER BY nomUsu
`

func (q *Queries) ListUsuario(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.Idu,
			&i.Nomusu,
			&i.Contrasenia,
			&i.Email,
			&i.Fechanac,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE usuario SET nomUsu = $2, contrasenia = $3, email = $4, fechaNac = $5  WHERE IDU = $1
`

type UpdateUsuarioParams struct {
	Idu         int32     `json:"idu"`
	Nomusu      string    `json:"nomusu"`
	Contrasenia string    `json:"contrasenia"`
	Email       string    `json:"email"`
	Fechanac    time.Time `json:"fechanac"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.Idu,
		arg.Nomusu,
		arg.Contrasenia,
		arg.Email,
		arg.Fechanac,
	)
	return err
}
