// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queriesMira.sql

package db

import (
	"context"
)

const createMira = `-- name: CreateMira :exec
INSERT INTO mira (IDP, IDU, gustoOno, calif) VALUES ($1, $2, $3, $4) RETURNING idp, idu, gustoono, calif
`

type CreateMiraParams struct {
	Idp      int32  `json:"idp"`
	Idu      int32  `json:"idu"`
	Gustoono string `json:"gustoono"`
	Calif    int32  `json:"calif"`
}

func (q *Queries) CreateMira(ctx context.Context, arg CreateMiraParams) error {
	_, err := q.db.ExecContext(ctx, createMira,
		arg.Idp,
		arg.Idu,
		arg.Gustoono,
		arg.Calif,
	)
	return err
}

const deleteMira = `-- name: DeleteMira :exec
DELETE FROM mira WHERE IDU = $1
`

func (q *Queries) DeleteMira(ctx context.Context, idu int32) error {
	_, err := q.db.ExecContext(ctx, deleteMira, idu)
	return err
}

const deleteMiraByIDs = `-- name: DeleteMiraByIDs :exec
DELETE FROM mira WHERE IDP = $1 AND IDU = $2
`

type DeleteMiraByIDsParams struct {
	Idp int32 `json:"idp"`
	Idu int32 `json:"idu"`
}

func (q *Queries) DeleteMiraByIDs(ctx context.Context, arg DeleteMiraByIDsParams) error {
	_, err := q.db.ExecContext(ctx, deleteMiraByIDs, arg.Idp, arg.Idu)
	return err
}

const getMira = `-- name: GetMira :many
SELECT idp, idu, gustoono, calif FROM mira WHERE IDU = $1
`

func (q *Queries) GetMira(ctx context.Context, idu int32) ([]Mira, error) {
	rows, err := q.db.QueryContext(ctx, getMira, idu)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mira
	for rows.Next() {
		var i Mira
		if err := rows.Scan(
			&i.Idp,
			&i.Idu,
			&i.Gustoono,
			&i.Calif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMira = `-- name: ListMira :many
SELECT idp, idu, gustoono, calif FROM mira ORDER BY calif
`

func (q *Queries) ListMira(ctx context.Context) ([]Mira, error) {
	rows, err := q.db.QueryContext(ctx, listMira)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mira
	for rows.Next() {
		var i Mira
		if err := rows.Scan(
			&i.Idp,
			&i.Idu,
			&i.Gustoono,
			&i.Calif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMira = `-- name: UpdateMira :exec
UPDATE mira SET gustoOno = $3, calif = $4 WHERE IDP = $1 AND IDU = $2
`

type UpdateMiraParams struct {
	Idp      int32  `json:"idp"`
	Idu      int32  `json:"idu"`
	Gustoono string `json:"gustoono"`
	Calif    int32  `json:"calif"`
}

func (q *Queries) UpdateMira(ctx context.Context, arg UpdateMiraParams) error {
	_, err := q.db.ExecContext(ctx, updateMira,
		arg.Idp,
		arg.Idu,
		arg.Gustoono,
		arg.Calif,
	)
	return err
}
