version: "3.9"

services:
  db:
    image: postgres:17.6
    container_name: postgres_peliculas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platpelis
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/postgresql/data

  app:
    image: golang:1.23
    container_name: servidor_go
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    # opcionalmente podrías poner aquí un comando por defecto
    command: make all

volumes:
  db_data:

