// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queriesPelicula.sql

package db

import (
	"context"
)

const createPeli = `-- name: CreatePeli :one
INSERT INTO pelicula (titulo, duracion, director, actores, edadMin, sinopsis, anioEstr) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING idp, titulo, duracion, director, actores, edadmin, sinopsis, anioestr
`

type CreatePeliParams struct {
	Titulo   string `json:"titulo"`
	Duracion int32  `json:"duracion"`
	Director string `json:"director"`
	Actores  string `json:"actores"`
	Edadmin  int32  `json:"edadmin"`
	Sinopsis string `json:"sinopsis"`
	Anioestr int32  `json:"anioestr"`
}

func (q *Queries) CreatePeli(ctx context.Context, arg CreatePeliParams) (Pelicula, error) {
	row := q.db.QueryRowContext(ctx, createPeli,
		arg.Titulo,
		arg.Duracion,
		arg.Director,
		arg.Actores,
		arg.Edadmin,
		arg.Sinopsis,
		arg.Anioestr,
	)
	var i Pelicula
	err := row.Scan(
		&i.Idp,
		&i.Titulo,
		&i.Duracion,
		&i.Director,
		&i.Actores,
		&i.Edadmin,
		&i.Sinopsis,
		&i.Anioestr,
	)
	return i, err
}

const deletePeli = `-- name: DeletePeli :exec
DELETE FROM pelicula WHERE IDP = $1
`

func (q *Queries) DeletePeli(ctx context.Context, idp int32) error {
	_, err := q.db.ExecContext(ctx, deletePeli, idp)
	return err
}

const getPeli = `-- name: GetPeli :one
SELECT idp, titulo, duracion, director, actores, edadmin, sinopsis, anioestr FROM pelicula WHERE IDP = $1
`

func (q *Queries) GetPeli(ctx context.Context, idp int32) (Pelicula, error) {
	row := q.db.QueryRowContext(ctx, getPeli, idp)
	var i Pelicula
	err := row.Scan(
		&i.Idp,
		&i.Titulo,
		&i.Duracion,
		&i.Director,
		&i.Actores,
		&i.Edadmin,
		&i.Sinopsis,
		&i.Anioestr,
	)
	return i, err
}

const listPelis = `-- name: ListPelis :many
SELECT idp, titulo, duracion, director, actores, edadmin, sinopsis, anioestr FROM pelicula ORDER BY titulo
`

func (q *Queries) ListPelis(ctx context.Context) ([]Pelicula, error) {
	rows, err := q.db.QueryContext(ctx, listPelis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pelicula
	for rows.Next() {
		var i Pelicula
		if err := rows.Scan(
			&i.Idp,
			&i.Titulo,
			&i.Duracion,
			&i.Director,
			&i.Actores,
			&i.Edadmin,
			&i.Sinopsis,
			&i.Anioestr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeli = `-- name: UpdatePeli :exec
UPDATE pelicula SET titulo = $2, duracion = $3, director = $4, actores = $5, edadMin = $6, sinopsis =$7, anioEstr =$8 WHERE IDP = $1
`

type UpdatePeliParams struct {
	Idp      int32  `json:"idp"`
	Titulo   string `json:"titulo"`
	Duracion int32  `json:"duracion"`
	Director string `json:"director"`
	Actores  string `json:"actores"`
	Edadmin  int32  `json:"edadmin"`
	Sinopsis string `json:"sinopsis"`
	Anioestr int32  `json:"anioestr"`
}

func (q *Queries) UpdatePeli(ctx context.Context, arg UpdatePeliParams) error {
	_, err := q.db.ExecContext(ctx, updatePeli,
		arg.Idp,
		arg.Titulo,
		arg.Duracion,
		arg.Director,
		arg.Actores,
		arg.Edadmin,
		arg.Sinopsis,
		arg.Anioestr,
	)
	return err
}
